### ISSUE TITLE
dtfabric.errors.FormatError: Unable to create struct object from data type definition with error: Struct() argument 1 must be string, not unicode

### ISSUE THREAD

**Issue by Lyro1** [log2timeline/plaso#2130]
I got this specific error when I try to run *log2timeline.py* :

```
Traceback (most recent call last):
File "/bin/log2timeline.py", line 68, in 
if not Main():
File "/bin/log2timeline.py", line 54, in Main
tool.ExtractEventsFromSources()
File "/usr/lib/python2.7/site-packages/plaso/cli/log2timeline_tool.py", line 369, in ExtractEventsFromSources
scan_context = self.ScanSource(self._source_path)
File "/usr/lib/python2.7/site-packages/plaso/cli/storage_media_tool.py", line 1083, in ScanSource
self._source_scanner.Scan(scan_context)
File "/usr/lib/python2.7/site-packages/dfvfs/helpers/source_scanner.py", line 565, in Scan
self._ScanNode(scan_context, scan_node, auto_recurse=auto_recurse)
File "/usr/lib/python2.7/site-packages/dfvfs/helpers/source_scanner.py", line 366, in _ScanNode
scan_node.path_spec, resolver_context=self._resolver_context)
File "/usr/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 55, in OpenFileEntry
path_spec_object, resolver_context=resolver_context)
File "/usr/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 158, in OpenFileSystem
resolver_helper = cls._GetResolverHelper(path_spec_object.type_indicator)
File "/usr/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 35, in _GetResolverHelper
from dfvfs.resolver_helpers import manager
File "/usr/lib/python2.7/site-packages/dfvfs/resolver_helpers/init.py", line 10, in 
from dfvfs.resolver_helpers import cpio_resolver_helper
File "/usr/lib/python2.7/site-packages/dfvfs/resolver_helpers/cpio_resolver_helper.py", line 10, in 
from dfvfs.vfs import cpio_file_system
File "/usr/lib/python2.7/site-packages/dfvfs/vfs/cpio_file_system.py", line 6, in 
from dfvfs.lib import cpio
File "/usr/lib/python2.7/site-packages/dfvfs/lib/cpio.py", line 43, in 
class CPIOArchiveFile(data_format.DataFormat):
File "/usr/lib/python2.7/site-packages/dfvfs/lib/cpio.py", line 59, in CPIOArchiveFile
'cpio_binary_big_endian_file_entry')
File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1881, in CreateDataTypeMap
return DataTypeMapFactory.CreateDataTypeMapByType(data_type_definition)
File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1899, in CreateDataTypeMapByType
return data_type_map_class(data_type_definition)
File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1412, in init
data_type_definition, self._data_type_map_cache)
File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1612, in _GetMemberDataTypeMaps
member_definition)
File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1899, in CreateDataTypeMapByType
return data_type_map_class(data_type_definition)
File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 246, in init
self._operation = self._GetByteStreamOperation()
File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 179, in _GetByteStreamOperation
return byte_operations.StructOperation(format_string)
File "/usr/lib/python2.7/site-packages/dtfabric/runtime/byte_operations.py", line 55, in init
'with error: {0!s}').format(exception))
dtfabric.errors.FormatError: Unable to create struct object from data type definition with error: Struct() argument 1 must be string, not unicode
```

I was running the script on Python 2.7.10 on a CentOS minimal distribution, and found [this topic](https://github.com/log2timeline/plaso/issues/1917), in which you were considering that updating Python to 2.7.10 and above could fix the problem.
I tried with the 2.7.15 version, which did not fix the issue.
I also changed from 2.7.15 to 3.6.3, which did not fix the issue.

I run the command like so : `log2timeline.py path/to/save.test plaso/test_data/syslog_image.dd`

Do you have any idea why this happens ?

**Comment by joachimmetz** [comment]
could you send the output from:
```
python -V
```

> Do you have any idea why this happens ?

An presumed older version of the struct module does not support a unicode string as a format argument.

**Comment by Lyro1** [comment]
That's weird, I just restarted my test laptop and `python -V` returns `Python 2.7.5`. I will try to fix this and set Python 2.7.15 as the default version and tell you if this fixed the issue.

**Comment by Lyro1** [comment]
After updating my default Python version as the 2.7.15, I got exactly the same error output as the first one I published. 
`python -V` returns now `Python 2.7.15`, and I runned exactly the same command as before.

I tried with Python 3.3.2, and I got the exame same error too.

Is there any way that log2timeline could run python 2.7.10 or below even if I changed my default version of Python ?

**Comment by Onager** [comment]
This still sounds to me like an old Python version. @Lyro1 can you please let us know:
- How you installed Plaso
- The exact commands you're running to change your python version

**Comment by Lyro1** [comment]
I installed Plaso by downloading the tar.gz archive from Github, running the *./configure* script and running *make*.
For the Python version, I just downloaded the Python 2.7.13 version, and made an alias of python in my bashrc like so : `alias python='/usr/bin/python2.7'`

I moved from CentOS to Debian, and it fixed my issue.

**Comment by joachimmetz** [comment]
I suspect that the issue persisted on CentOS due to the Python 2 site-packages/dist-packages still pointing to the 2.7.5 versions instead of 2.7.13 bundled ones.

**Comment by joachimmetz** [comment]
I close this issue for now.

**Comment by LawrenceRRogers** [comment]
I encountered this problem too in my test environment. I have re-engineered Plaso version 20181219 release 3 to use Python Virtual Environments and the CentOS/RHEL Software Collections Library (SCL). The version of Python in the SCL is 2.7.13 and this works and plays well with this version of Plaso. I released this today, Friday, January 11, 2019. See the notice here: http://www.cert.org/forensics/repository.
